#!/usr/local/bin/bash

# CLEAN DS_STORE
find . -type f -name '*.DS_Store' -ls -delete 1>/dev/null

# Verification de l'accessibilité de l'ordinateur

host="familial"
read -e -i "$host" -p "Where: " input
host="${input:-$host}"






connected=`ssh -o BatchMode=yes -o ConnectTimeout=5 $host echo 1 2>/dev/null || echo 0`



if [ $connected -eq 1 ]
then
# Liste des dossiers à sauvegarder
		echo -e "\n\033[32;mBackup ongoing\033[0;m"
		rsync -arvz --progress --delete $1 $host:/home/tom/backup/mac15.tom/ponctuel/

else
		echo -e "\n\033[31;m$host hors ligne\033[0;m\n"
fi








