#!/usr/local/bin/bash
black='\033[0;30m'
gray='\033[1;30m'
darkred='\033[0;31m'
pink='\033[1;31m'
darkgreen='\033[0;312m'
lightgreen='\033[1;32m'
orange='\033[0;33m'
yellow='\033[1;33m'
deepblue='\033[0;34m'
lightblue='\033[1;34m'
deeppurple='\033[0;35m'
lightpurple='\033[1;35m'
darkcyan='\033[0;36m'
lightcyan='\033[1;36m'
lightgray='\033[0;37m'
white='\033[1;37m'

neutre='\033[0;m'

declare -a ListColors=(black gray darkred pink darkgreen lightgreen orange yellow deepblue lightblue deeppurple lightpurple darkcyan lightcyan white neutre)


a=0
col=30
for i in "${ListColors[@]}" 
do
		echo -e "\033[$a;$col;m $i \\033\[$a;$col;m ${neutre}"
	 	if [ $a -eq 0 ]; then
				a=1
		else
				a=0
				col=$((col +1))
		fi
done




