#!/usr/local/bin/bash



# Télécharger le fichier d'interet

if [[ "$1" == *torrent ]]
then
		aria2c -c --seed-time=0 "$1"
else
   echo -e "\033[35mSave as : \033[0m"
	 read name 
	 wget -c -v -O "$name" "$1" 
fi
curl "https://smsapi.free-mobile.fr/sendmsg?user=28628108&pass=3ymqZMHBVYuxAU&msg=Download de $name terminé"

exit







