#!/usr/local/bin/bash

echo -e "\033[35mSave as : \033[0m"
read name


# Télécharger le fichier d'interet


if [[ "$1" == *torrent ]]; then
    aria2c -c --seed-time=0 --index-out=1="$name" ~/Downloads/"$1"
else
    wget -c -O "$name" "$1" 
fi

curl "https://smsapi.free-mobile.fr/sendmsg?user=28628108&pass=3ymqZMHBVYuxAU&msg=Download de $name terminé"




exit








