#!/usr/local/bin/bash

# Monter la freebox
sudo mount -t cifs //mafreebox.freebox.fr/Disque\ dur/ /media/freebox/ -o user=freebox,password=Pyosta6ne,uid=1000,gid=1000,rw && cd /media/freebox/

# Télécharger le fichier d'interet
cd ~/Downloads/
wget $1
curl "https://smsapi.free-mobile.fr/sendmsg?user=28628108&pass=3ymqZMHBVYuxAU&msg=Téléchargement de $1 terminé."
filename=$( /bin/ls -t . | head -1 )

# Copier le fichier d'interet sur la FB
scp $filename /media/freebox/Vidéos/$2

# Ejecter la FB
cd ~ && sudo umount /media/f\reebox

# Notification
curl "https://smsapi.free-mobile.fr/sendmsg?user=28628108&pass=3ymqZMHBVYuxAU&msg=Transfert de $2 terminé."
tmux kill-session
exit








