#!/usr/local/bin/bash
#DEFINITION DES VARIABLES DU NOUVEAU TITRE

echo -e  "\033[36mCible (fichiers a renommer)\033[0m"
read cible

echo -e "\033[36mSerie name\033[0m"
read serie_name

echo -e "\033[36mSeason number\033[0m"
read  season_number


echo -e "\033[36mLanguage (default VOSTFR)\033[0m" 
read language
language=${language:VOSTFR}

#CODAGE NOUVEAU TITRE
for f in *$cible*
do fn=`echo $f|sed  's/^.*\([Ss]0..\)//p'`
   ext=`echo $f|tail -c4`
   fn1=`echo $fn|head -c2`
   fn2=`echo "$serie_name".S"$season_number"E"$fn1"."$language"."$ext"`
   mv "$f" "$fn2"
done
	 
